In [1]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Read data
df = pd.read_csv("../Data.csv")

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
# dependent variable, y = Purchased
# independent variables, X = Country, age, salary

In [73]:
X = df.iloc[:,:-1].values

In [57]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [47]:
y = df.iloc[:,3:].values

In [48]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [23]:
# As you can see there are missing values in independent variables
# as they are continous valued we can imput them

In [32]:
from sklearn.preprocessing import Imputer

In [33]:
imputer = Imputer(missing_values='NaN', strategy='mean')

In [27]:
imputer = imputer.fit(X[:,1:3])

In [74]:
X[:,1:3] = imputer.transform(X[:,1:3])

In [29]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
# or directly use fit_transform

In [75]:
X[:,1:3] = imputer.fit_transform(X[:,1:3])

In [76]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
# Categorical Data 
# the country and Purchased are categorical that needs to be changed to numerical

In [37]:
from sklearn.preprocessing import LabelEncoder

In [59]:
labelencoder_country = LabelEncoder()

In [77]:
X[:,0] = labelencoder_country.fit_transform(X[:,0])

In [78]:
X[:,0]

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=object)

In [43]:
labelencoder_purchased = LabelEncoder()

In [49]:
y[:,0] = labelencoder_country.fit_transform(y[:,0])

In [50]:
y

array([[0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1]], dtype=object)

In [51]:
# encoding the categorical data

In [52]:
from sklearn.preprocessing import OneHotEncoder

In [70]:
onehotencoder = OneHotEncoder(categorical_features=[0])

In [79]:
X = onehotencoder.fit_transform(X).toarray()

In [80]:
X

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.40000000e+01,   7.20000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          2.70000000e+01,   4.80000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          3.00000000e+01,   5.40000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.80000000e+01,   6.10000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          4.00000000e+01,   6.37777778e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          3.50000000e+01,   5.80000000e+04],
       [  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          3.87777778e+01,   5.20000000e+04],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          4.80000000e+01,   7.90000000e+04],
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00,
          5.00000000e+01,   8.30000000e+04],
       [  1.00000000e+00,   0.0000000

In [81]:
# get dummies in pandas can also be used for OHE
# pandas get_dummies can work with string

In [86]:
pd.get_dummies(df)

Age   Salary  Country_France  Country_Germany  Country_Spain  \
0  44.0  72000.0             1.0              0.0            0.0   
1  27.0  48000.0             0.0              0.0            1.0   
2  30.0  54000.0             0.0              1.0            0.0   
3  38.0  61000.0             0.0              0.0            1.0   
4  40.0      NaN             0.0              1.0            0.0   
5  35.0  58000.0             1.0              0.0            0.0   
6   NaN  52000.0             0.0              0.0            1.0   
7  48.0  79000.0             1.0              0.0            0.0   
8  50.0  83000.0             0.0              1.0            0.0   
9  37.0  67000.0             1.0              0.0            0.0   

   Purchased_No  Purchased_Yes  
0           1.0            0.0  
1           0.0            1.0  
2           1.0            0.0  
3           1.0            0.0  
4           0.0            1.0  
5           0.0            1.0  
6           1.0            0.0  
7           0.0            1.0  
8           1.0            0.0  
9           0.0            1.0

In [87]:
df.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')