In [2]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('../instructor/Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values



In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:] # removing col 0 for escaping dummy variable trap




In [5]:
X

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.02000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   7.09000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  1.00000000e+00,   0.00000000e+00,   7.72000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   7.92000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [6]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train.shape

(8000, 11)

In [8]:
import keras
from keras.models import Sequential
from keras.layers import Dense

Using Theano backend.
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'C:\\Users\\JITHUR~1\\AppData\\Local\\Temp\\try_flags_5a82s78y.c:4:10: fatal error: cudnn.h: No such file or directory\r\n #include <cudnn.h>\r\n          ^~~~~~~~~\r\ncompilation terminated.\r\n'
Mapped name None to device cuda: GeForce 610M (0000:01:00.0)


In [9]:
# initialising the nn

In [10]:
classifier = Sequential()

In [11]:
# adding the first input layer and hidden layer/
classifier.add(Dense(output_dim=6, init='uniform', activation='relu', input_shape=(11,) ))

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_shape=(11,), units=6, kernel_initializer="uniform")`
  from ipykernel import kernelapp as app


In [12]:
classifier.add(Dense(output_dim=6,init='uniform', activation='relu'))

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  if __name__ == '__main__':


In [13]:
classifier.add(Dense(output_dim=1, init='uniform',activation='sigmoid'))

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  if __name__ == '__main__':


In [ ]:
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
classifier.fit(X_train,y_train,batch_size=10,epochs=50, verbose=1)

Epoch 1/50
8000/8000 [==============================] - 1s - loss: 0.4898 - acc: 0.7955     

In [17]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [19]:
y_pred = classifier.predict(X_test)

In [20]:
y_pred[:5]

array([[ 0.15510944],
       [ 0.36309263],
       [ 0.18095808],
       [ 0.06136096],
       [ 0.10379466]], dtype=float32)

In [22]:
y_pred = (y_pred > 0.5) # 0.5 threshold

In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
cm = confusion_matrix(y_test, y_pred)

In [25]:
cm

array([[1550,   45],
       [ 263,  142]])

In [26]:
(1550+142)/2000

0.846

In [28]:
# 84.6% accuracy for 46 epochs