In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
dataset = pd.read_csv("../instructor/Restaurant_Reviews.tsv",sep='\t',quoting=3) # for removing quotes

In [6]:
dataset.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [38]:
dataset.shape

(1000, 2)

In [7]:
# cleaning text

In [31]:
import re
import nltk
# nltk.download("stopwords")
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [9]:
dataset['Review'][0]

'Wow... Loved this place.'

In [34]:
# keeping only letters
review = re.sub("[^a-zA-Z]"," " ,dataset['Review'][0])
review = review.lower()
review = review.split()
review

['wow', 'loved', 'this', 'place']

In [35]:
# stop word removal and stemming
review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
review = ' '.join(review)
review

'wow love place'

In [41]:
corpus = []
for i in range(0,1000):
    review = re.sub("[^a-zA-Z]"," " ,dataset['Review'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [42]:
corpus[:5]

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price']

In [53]:
# bag of words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()


In [54]:
#X = cv.fit_transform(corpus)

In [55]:
#X[:4]

<4x1565 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [56]:
X = cv.fit_transform(corpus).toarray()

In [57]:
X[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [49]:
corpus[:4]

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love']

In [ ]:
# we can remove irrevelant words like rick, steve with max_features

In [59]:
cv = CountVectorizer(max_features=1500) # the 1500 most used features
#X = cv.fit_transform(corpus)#.toarray()
#X[:4]

<4x1500 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [60]:
X = cv.fit_transform(corpus).toarray()
X[:4]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [61]:
y = dataset.iloc[:,1].values

In [62]:
y[:4]

array([1, 0, 0, 1], dtype=int64)

In [63]:
# naive bayes
# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)



# Fitting classifier to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train,y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

C:\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


array([[ 67,  50],
       [ 20, 113]])